Add filepath to error messages, not filenames

diff --git a/bin/adjust-mtime-and-name b/bin/adjust-mtime-and-name
--- a/bin/adjust-mtime-and-name
+++ b/bin/adjust-mtime-and-name
@@ -54,7 +54,7 @@ do
     then
         timestamp=`echo "$filename" | sed -E 's/.*([0-9]{4})[^0-9]([0-9]{2})[^0-9]([0-9]{2})[^0-9]+([0-9]{2})[^0-9]([0-9]{2})[^0-9]([0-9]{2}).*/\1\2\3\4\5.\6/'`
     else
-        echo "Could not extract timestamp from filename '$filename'" >&2
+        echo "Could not extract timestamp from file '$filepath'" >&2
         exit_code=1
         continue
     fi
@@ -64,7 +64,7 @@ do
     if
         [[ ! "$timestamp" =~ ^[0-9]{12}\.[0-9]{2}$ ]]
     then
-        echo "Internal error: Ill-formed timestamp '$timestamp' from filename '$filename'" >&2
+        echo "Internal error: Ill-formed timestamp '$timestamp' from file '$filepath'" >&2
         exit 1
     fi
 
@@ -121,7 +121,7 @@ do
         if
             [[ "$filehash" != "$newfilehash" ]]
         then
-            echo "Cannot overwrite file '$newfilepath' with different hash than '$filename'" >&2
+            echo "Cannot overwrite file '$newfilepath' with different hash than '$filepath'" >&2
             exit_code=1
             continue
         fi
