Only exit on internal errors

diff --git a/bin/adjust-mtime-and-name b/bin/adjust-mtime-and-name
--- a/bin/adjust-mtime-and-name
+++ b/bin/adjust-mtime-and-name
@@ -10,6 +10,8 @@ then
     exit 1
 fi
 
+exit_code=0
+
 for filename in "$@"
 do
     ## Make sure filename points to a file
@@ -18,12 +20,14 @@ do
         [[ ! -e "$filename" ]]
     then
         echo "File does not exist: $filename" >&2
-        exit 1
+        exit_code=1
+        continue
     elif
         [[ ! -f "$filename" ]]
     then
         echo "Not a file: $filename" >&2
-        exit 1
+        exit_code=1
+        continue
     fi
 
     ## Extract timestamp from filename
@@ -46,7 +50,8 @@ do
         timestamp=`echo "$filename" | sed -E 's/.*([0-9]{4})[^0-9]([0-9]{2})[^0-9]([0-9]{2})[^0-9]+([0-9]{2})[^0-9]([0-9]{2})[^0-9]([0-9]{2}).*/\1\2\3\4\5.\6/'`
     else
         echo "Could not extract timestamp from filename '$filename'" >&2
-        exit 1
+        exit_code=1
+        continue
     fi
 
     ## Extract extension from filename
@@ -66,7 +71,7 @@ do
     if
         [[ -z "$filehash" ]]
     then
-        echo "Could not compute the SHA-1 hash of '$filename'" >&2
+        echo "Internal error: Could not compute the SHA-1 hash of '$filename'" >&2
         exit 1
     fi
 
@@ -76,7 +81,7 @@ do
         [[ ! "$timestamp" =~ ^[0-9]{12}\.[0-9]{2}$ ]]
     then
         echo "Internal error: Ill-fomed timestamp '$timestamp' from filename '$filename'" >&2
-        exit 2
+        exit 1
     fi
 
     ## Construct new filename
@@ -87,7 +92,7 @@ do
         [[ ! $datestring =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}-[0-9]{2}-[0-9]{2}$ ]]
     then
         echo "Internal error: Ill-formed CCYY-MM-DD_HH-mm-ss date string '$datestring'" >&2
-        exit 2
+        exit 1
     fi
 
     shortened_filehash=`echo $filehash | head -c5`
@@ -96,7 +101,7 @@ do
         [[ ! $shortened_filehash =~ ^[0-9a-fA-F]+$ ]]
     then
         echo "Internal error: Ill-formed hexstring '$shortened_filehash'" >&2
-        exit 2
+        exit 1
     fi
 
     newfilename=${datestring}__${shortened_filehash}${extension}
@@ -111,14 +116,16 @@ do
         if
             [[ "$filehash" != "$newfilehash" ]]
         then
-            echo "Tried to overwrite file '$newfilename' with different hash than '$filename'" >&2
-            exit 1
+            echo "Cannot overwrite file '$newfilename' with different hash than '$filename'" >&2
+            exit_code=1
+            continue
         fi
     elif
-        [[ -e "$newfilename" ]]
+        [[ -d "$newfilename" ]]
     then
-        echo "Tried to overwrite '$newfilename', which already exists" >&2
-        exit 1
+        echo "Cannot overwrite '$newfilename', because it is a directory" >&2
+        exit_code=1
+        continue
     fi
 
     ## Adjust timestamp of file
@@ -133,3 +140,7 @@ do
         mv -v "$filename" "$newfilename"
     fi
 done
+
+## Exit with code
+
+exit $exit_code
